[package]
name = "sample-robot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

binrobot-rs = { git = "https://github.com/anosatsuk124/binrobot-rs.git" }

